env:
  commonjs: true
  es2021: true
  node: true
extends:
  - 'airbnb-base'
  - 'plugin:prettier/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  'prettier/prettier': ['error']
  'no-unused-vars': ['error', { argsIgnorePattern: 'next' }]
